apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb
    jsonData:
      version: Flux
      organization: acme-corp
      defaultBucket: ignition
      tlsSkipVerify: true
    secureJsonData:
      token: secret-auth-token
    editable: true
